// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKgP26lDgkCnEcxKiC-vLMAg8kTGN01TU',
    appId: '1:905066560747:web:3e07bd878224d223f192ae',
    messagingSenderId: '905066560747',
    projectId: 'realchat-89c04',
    authDomain: 'realchat-89c04.firebaseapp.com',
    storageBucket: 'realchat-89c04.firebasestorage.app',
    measurementId: 'G-XP823W410M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2HQxCAWmRzCtxRUSHPgzA4b2nizdTiXs',
    appId: '1:905066560747:android:3eaf0d527e595039f192ae',
    messagingSenderId: '905066560747',
    projectId: 'realchat-89c04',
    storageBucket: 'realchat-89c04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN0oz0OGLM3YWB5QyVL_jUofuTngBgc9M',
    appId: '1:905066560747:ios:c2fca7abcfb027a3f192ae',
    messagingSenderId: '905066560747',
    projectId: 'realchat-89c04',
    storageBucket: 'realchat-89c04.firebasestorage.app',
    androidClientId: '905066560747-n162ck687bevgerbh9kh4kpos4cnsm5h.apps.googleusercontent.com',
    iosClientId: '905066560747-4cqu2eq078bcguae4j208ank60ik1jua.apps.googleusercontent.com',
    iosBundleId: 'com.example.realchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN0oz0OGLM3YWB5QyVL_jUofuTngBgc9M',
    appId: '1:905066560747:ios:c2fca7abcfb027a3f192ae',
    messagingSenderId: '905066560747',
    projectId: 'realchat-89c04',
    storageBucket: 'realchat-89c04.firebasestorage.app',
    androidClientId: '905066560747-n162ck687bevgerbh9kh4kpos4cnsm5h.apps.googleusercontent.com',
    iosClientId: '905066560747-4cqu2eq078bcguae4j208ank60ik1jua.apps.googleusercontent.com',
    iosBundleId: 'com.example.realchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKgP26lDgkCnEcxKiC-vLMAg8kTGN01TU',
    appId: '1:905066560747:web:7d188c53e33bb66bf192ae',
    messagingSenderId: '905066560747',
    projectId: 'realchat-89c04',
    authDomain: 'realchat-89c04.firebaseapp.com',
    storageBucket: 'realchat-89c04.firebasestorage.app',
    measurementId: 'G-W69QT4Q058',
  );
}
